### ISSUE TITLE
鑄造 LUN 代幣

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#1]
在 TGE 開始前，我們會先需要有 LUN 合約地址讓大家知道我們發行合約的資訊。

此代幣的規格草案如下：
- symbol: LUN
- total supply: 1,000,000
- decimals: 18
- 不可升級
- 可以燒毀 burnable

這項工作會需要完成幾件事情：
- [ ] 發行代幣
- [ ] 於 Etherscan 驗證源碼
- [ ] 將代幣轉至社群的 Gnosis Safe 合約中

**Comment by yurenju** [comment]
@hydai 可以幫忙看一下有沒有什麼要修改的？

**Comment by hydai** [comment]
上面的規格符合我們初版的預期，這部分沒有需要修改的。

**Comment by yurenju** [comment]
@hydai 那我們來分一下工作好了，你想做 #2 還是 deploy token 呀？兩個我都可以

**Comment by hydai** [comment]
我來做這個吧

**Comment by hydai** [comment]
Done.

代幣發行：https://etherscan.io/tx/0xa9e9ed2e0963a882d4165200c43c4c9e94ba1a8f0398a8c114bd3344e188abc7
驗證：https://etherscan.io/address/0xd6b5f077c56e94de018e34d4908f36848b2c9d3f#code
轉到 gnosis safe：https://etherscan.io/tx/0x6f313dc2f40f32baad97681557670e345400101daca5d1d975907328b42c3a32
