### ISSUE TITLE
計算根據 ETH 比例所分配的 LUN 代幣數量

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#12]
在 TGE 結束後，我們需要一個 script 來統計特定兩個區塊之間，每個 account 所發送的 ETH 數量，再基於此數據計算出每個地址要分配多少 LUN。

輸入：
- 合約地址（社群金庫的地址）
- 起始區塊
- 結束區塊

輸出：
- 結構化的資料如 JSON 或 CSV
- 每列應該要有：地址、ETH 數量、應發 LUN 數量

因為初期治理框架還沒確定，不過完成此 script 會發送 LUN 作為獎勵，數量待定。

**Comment by yurenju** [comment]
開了一個新的 repository [lun-dao/lun-utils][1]，如果想幫忙這個的人就發一個 PR 到那個 repository 吧

[1]: https://github.com/lun-dao/lun-utils

**Comment by hydai** [comment]
https://github.com/lun-dao/lun-utils/commit/68846a53b9d1aa2baecb9c9187f1e822410ad537

我先丟了一版 alpha 版本，裡面沒有做任何的錯誤保護XD

**Comment by yurenju** [comment]
@hydai 感覺還要稍微改一下，比如說把相同地址的累加再一起

**Comment by hydai** [comment]
@yurenju 
進化了： https://github.com/lun-dao/lun-utils/commit/61223fb00216a6038e64b5684dfeadef4f5ca1a5

現在會把相同地址的加起來
