### ISSUE TITLE
設置 snapshot

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#16]
snapshot 是一套無需 gas 的治理工具，主要是用 sign message 的方式投票，同時也可以用不同的 Strategy 來調整 voting power 要怎麼分配。在 README 裡面有提到我們會採用 snapshot 作為治理工具，這個工作是先將 snapshot 基礎的設定好，往後如果要修改 strategy 也可以再更改。

因為會需要在 ens 上面加新的 record，所以就我先開始做了，也會需要 @hydai 幫忙簽名送出交易。

**Comment by yurenju** [comment]
@hydai 要請你簽名一下，這是 snapshot 要設定 ens 的部分，會新增一個 text record，然後把 snapshot 提供的 ipfs 位址填進去。交易發出去之後再跟我說一聲，另外 ETH 如果需要補貼，等 TGE 結束後我們可以從營運的部分分配一些 ETH 給我們兩個作為日常營運用。

https://gnosis-safe.io/app/eth:0x5Ab62C4Eefb34E8E162e651Ea371410426454275/transactions/queue

![image](https://user-images.githubusercontent.com/22155/148206136-f0336a75-773e-4210-88c7-92390c3be041.png)

**Comment by hydai** [comment]
Done.

**Comment by yurenju** [comment]
還有些事情要設定的

**Comment by yurenju** [comment]
設定好囉！
https://snapshot.org/#/lundao.eth
