### ISSUE TITLE
用 Docusaurus 架設靜態網頁

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#18]
經討論後我們決定採用 Docusaurus 架設靜態網頁，主要有以下工作：
- [ ] 導入 Docusaurus
- [ ] 設定 github action 自動發佈到 gh-pages

因為 @gasolin 有使用經驗，會請他幫忙這個設置。

### Discussed in https://github.com/lun-dao/LunDAO/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **gasolin** January  5, 2022</sup>
作為一個目的為產出中深度文章的DAO, 選擇靜態網站產生器也是個重點?

我建議從支援以下兩者為基礎來挑選

1. 可以 host 在 github 上

用類似 EIP 的形式，開 PR 投稿，
直接 host 在 https://github.com/lun-dao/LunDAO gh-pages branch 
這樣產出更清楚

2. 可以自動透過 github action 產生網站

文章被接受 (merge) 後自動化發布，減少手動工作

第三個考量是是否要規定為 Markdown 格式

https://jamstack.org/generators/ 上列出了一些選擇

常見的

- Gatsby https://jamstack.org/generators/gatsby/
- Docusaurus https://docusaurus.io/
</div>

**Comment by gasolin** [comment]
可以自動部署了 https://lun-dao.github.io/LunDAO/

**Comment by yurenju** [comment]
謝啦！關囉
