### ISSUE TITLE
建立社群溝通管道 (Telegram, Discord 或其他)

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#3]
在 TGE 前我們會需要先建立一個社群可以詢問的地方，一般加密貨幣社群都是用 Telegram 或 Discord，我們可以考慮一下哪一個比較適合我們。

工作事項：
- [x] 決定要用什麼平台 -> 決定用 Discord
- [x] 建立群組
- [x] 更新群組的加入連結到 README

**Comment by hydai** [comment]
就我所知，Discord 在進行討論的時候能通過多頻道的方式來進行不同類別話題的分類，但 Telegram 目前多為連續且直線的聊天歷史，比較難做好的討論與追蹤。

如果只是需要單純的討論大廳，那 Telegram 可行。
若需要能夠分類的社群，那 Discord 會比較合適。

**Comment by yurenju** [comment]
那我們用 Discord 如何？以後如果有提案要討論的話可以開一個頻道來討論，比如說以後我們有 LIPs repository 來放提案，裡面的其中一個提案 lip-1，我們就可以在 Discord 上開一個群組 #lip-1 來討論。

**Comment by hydai** [comment]
可以，這樣很方便

**Comment by yurenju** [comment]
建立好了 @hydai  有空加一下
https://discord.gg/z5GDrSSHZH

**Comment by yurenju** [comment]
在 commit 9d3dba4 加入了 discord invitation link
