### ISSUE TITLE
修改 discord github integration 會丟出來的事件

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#37]
github-action 系列的應該都不用出現，比較重要的應該是討論的部分：issue 的開啟、關閉、留言，Discussion 的開啟、留言等。總之移除掉 github-action 應該就行。

![image](https://user-images.githubusercontent.com/22155/148465017-ae11f771-00e3-45c2-9e9f-89d645bb44b0.png)

**Comment by hydai** [comment]
Fixed.
