### ISSUE TITLE
更新 TGE 合約地址連結

### ISSUE THREAD

**Issue by gasolin** [lun-dao/LunDAO#43]
一樣的地址，但改連到 https://etherscan.deth.net/address/0xd6b5f077c56e94de018e34d4908f36848b2c9d3f#code 更清楚

**Comment by yurenju** [comment]
我覺得保持 etherscan 的會比較好，主因是 etherscan 除了提供源碼以外，還有交易紀錄以及實際可以執行、讀取合約的地方：
![image](https://user-images.githubusercontent.com/22155/148684051-154ce334-5751-488a-9857-20766b2988c5.png)
![image](https://user-images.githubusercontent.com/22155/148684064-50c6ff67-90bd-4d0a-b62d-6b21546a50c4.png)

deth 比較注重在更清晰的源碼展示，但是其他功能比較缺乏。反觀 etherscan 也有源碼，雖然沒有 Deth 顯示的清楚，但是額外的功能還是會讓我覺得放連結指到 etherscan 會比較好。
