### ISSUE TITLE
TGE 代幣分配

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#58]
TGE 已經結束一陣子了，我原本就規劃了 10 ETH 作為起始資金，雖然沒有其他人投入資金，不過這筆資金還是足夠讓我們繼續實驗這個計畫。根據 TGE 的規則我們會把 LUN 代幣依照以下比例分配：

![image](https://user-images.githubusercontent.com/22155/149330174-3ea4b769-3870-4d25-9364-a75b4ea36825.png)
[LUN TGE 試算表][1]

這些 LUN 代幣會在 Arbitrum 上面發送，等等我會先發起一個社群金庫的簽名讓大家檢視。另外之前有提到 coordinape 的實驗，我想等這個代幣分配結束，我們約個時間一起做做看，我會再另外開一個 issue 來執行。

[1]: https://docs.google.com/spreadsheets/d/1ymq189PWpGpllTnWVaE3AUiaXKV1uRBnDUIbWsVNVzU/edit#gid=0

**Comment by yurenju** [comment]
社群金庫針對 TGE 代幣分配的 tx 初始化了，但是還沒發出去。大家可以看一下是不是跟上面的試算表是相符的，如果沒問題明天再請 @hydai 幫忙簽發 ：

https://gnosis-safe.io/app/arb1:0xC2bEeC7a39Ea549F72d937E7b5951B8ee0C8d295/transactions/0xa98a01dd78a598ccc3922d3408bf7b6498aef7a5d3bbfc7283dae177efc0445c
![image](https://user-images.githubusercontent.com/22155/149331955-281c65cb-91da-4633-a0b6-10ee657d6746.png)

**Comment by yurenju** [comment]
@hydai gogo~ 如果你沒有 ETH 可以選擇只簽名，我可以執行 :D

**Comment by hydai** [comment]
> @hydai gogo~ 如果你沒有 ETH 可以選擇只簽名，我可以執行 :D

可能要麻煩你執行，我還沒在 arb 上面搞 eth :-(

**Comment by yurenju** [comment]
送出囉！ @iisaint @hydai 可以確認一下是不是有在 Arbitrum 網路收到 :D

**Comment by hydai** [comment]
我在 Arbitrum 上面收到了

**Comment by gasolin** [comment]
@yurenju 網站上金庫的地址要改成這個嗎？

**Comment by yurenju** [comment]
@gasolin 金庫地址現在有兩個了，一個是 ethereum 另外一個是 arbitrum
