### ISSUE TITLE
使用 coordinape 分配 TGE 前社群參與的 LUN 代幣

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#59]
coordinape 是一個由每個社群成員互相各自決定代幣分配比例的服務，使用這個服務時，每個人都會有固定的 GIVE 點數，並且可以分配點數給其他的團隊成員。分配時請先思考你最近都跟哪些社群成員一起工作、你認為哪些成員為社群讓社群增進了更多價值，衡量之後把 GIVE 點數分配給這些社群成員。

近期內我會組織一次 coordinape 的分配，大家可以一起試試。

- [x] 組織 coordinape 的分配
- [x] 發送分配 5000 LUN
- [ ] 寫一篇頁面紀錄結果

### Discussed in https://github.com/lun-dao/LunDAO/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **yurenju** January  6, 2022</sup>
因為我們還沒開始放流動性，所以 LUN 代幣目前的價格也是未知，同時在這個時候其實大家已經開始貢獻專案了如參與討論、寫統計腳本跟架設靜態網頁產生器等。我想要先分配一些 LUN 來給 TGE 完成前的。

因為現在的規劃日常營運會有 200,000 LUN 可以使用，我想說我們先用約 5,000 LUN 分配給目前的貢獻者，然後或許試試看 [coordinape][1] 到底怎麼使用。理論上他是一個讓每個人思考一段時間內大家在社群裡面的合作對象，然後給他一個權重，最終會產生一個節點圖，照著這個節點圖分配獎勵。

可以參考以下影片看看 coordinape 到底是怎麼運作，也想知道大家有什麼其他的想法。

[![Coordinape 說明影片](http://img.youtube.com/vi/J8oGun8EKDE/0.jpg)](http://www.youtube.com/watch?v=J8oGun8EKDE)

[1]: https://coordinape.com/</div>

**Comment by yurenju** [comment]
用 MetaMask 連接後，你可以到 Allocate 頁面點選 My Epoch 寫下你自己在這段期間的貢獻，不論是提出討論、執行工作、撰寫文件或是協助組織都是貢獻的一部份。選擇 Opt In 可以讓你收到 GIVE 點數的分配，選擇 Opt out 代表你有別的管道獲得獎勵了。為了測試請大家這次都選 Opt In。

![image](https://user-images.githubusercontent.com/22155/149647920-8ac7e930-5dce-4f39-b80a-26da2221bbb4.png)

接下來第二個 tab 是 Select Team，這次可以先選擇所有人 Select All。

![image](https://user-images.githubusercontent.com/22155/149648031-6d88ed10-0079-4bc6-8961-3d34689693db.png)

最後一頁 Allocate GIVE 就是讓大家把手上的 GIVE 點數分配給其他社群成員，之後我們第一次的分發 5,000 LUN 就會依照這個比例分發給大家。如果你認為有什麼人我漏加到了，但他確實對社群有貢獻，請用  Vouching 功能把他加入。

**Comment by yurenju** [comment]
現在的分配圖長這樣，等大家分配 GIVE 點數後應該會慢慢長大 XD
![image](https://user-images.githubusercontent.com/22155/149648375-89420b55-e7ae-4cfd-9b68-eefc83a92377.png)

**Comment by yurenju** [comment]
我們  coordinape 的結果出來囉，接下來我會先把 LUN 分配下去，並且用一個頁面紀錄。


|No.|name       |address                                   |received|sent|epoch number|Date                   |FIELD8|5000 LUN distribution|
|---|-----------|------------------------------------------|--------|----|------------|-----------------------|------|---------------------|
|2  |chnejohnson|0x96a4715280c3dac3f3093d51aa278aa5eb60ffde|37      |100 |1           |2022/01/16 - 2022/01/21|      |232.7044025          |
|3  |gasolin    |0xfda995eb398750319a2d5e8a4766c02e54db24b8|168     |100 |1           |2022/01/16 - 2022/01/21|      |1056.603774          |
|4  |hydai      |0x9a76d78f203ec6f7289bb0178cb6c25f18a9911e|103     |100 |1           |2022/01/16 - 2022/01/21|      |647.7987421          |
|5  |iisaint    |0x9b98b59388bdcf8dbac81bb7f3cd6910b712f85e|82      |100 |1           |2022/01/16 - 2022/01/21|      |515.7232704          |
|6  |kimiwu123  |0x352a9d61537063781d5bdab36e8dccf540d6a595|48      |100 |1           |2022/01/16 - 2022/01/21|      |301.8867925          |
|7  |moojing    |0x8865d9736ad52c6cdbbea9bcd376108284cfd0e4|28      |0   |1           |2022/01/16 - 2022/01/21|      |176.1006289          |
|8  |quesalltime|0x0b7bb1a65b9400a2a3271fcbf0443d85871231e3|105     |100 |1           |2022/01/16 - 2022/01/21|      |660.3773585          |
|9  |wiasliaw   |0x66fa22aefb2cf14c1fa45725c36c2542521c0d3e|17      |0   |1           |2022/01/16 - 2022/01/21|      |106.918239           |
|10 |yurenju    |0x8fa26cda1a3a8c0c89d01261689a63418d436d24|193     |100 |1           |2022/01/16 - 2022/01/21|      |1213.836478          |
|11 |zjiekai    |0x9d1870d70f197bdf59b996bb31a20ffed2ffca87|14      |100 |1           |2022/01/16 - 2022/01/21|      |88.05031447          |

**Comment by yurenju** [comment]
@hydai  請幫我檢查一下這個 tx 的內容對不對
https://gnosis-safe.io/app/arb1:0xC2bEeC7a39Ea549F72d937E7b5951B8ee0C8d295/transactions/0x6b8f37ce87b431bb53cf36629bc035cbab9d85a596fbc5c7e328bb708e0ac332

我有自己把比較好檢查的地址（前面加 `arb1:`）跟 decimals 18 寫在這個 google spreadsheet，不過還是請你試著算幾個看看 decimals 有沒有弄錯
https://docs.google.com/spreadsheets/d/1xoup8YWQ-8hCPU7YA76dCEghMZ2_n3eRYYou1VREC3I/edit#gid=1703167312

**Comment by hydai** [comment]
@yurenju 我檢查完了，這 10 筆都正確已經 approved.

**Comment by yurenju** [comment]
送出囉！
https://arbiscan.io/tx/0x2a43bc74dc232ea259f04dbd135be2bbb898a0017755afbb3f9ab41da47b7d1c

等紀錄頁面建立後我再關閉這個 issue
