### ISSUE TITLE
整理 README 把 TGE 歸檔

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#61]
TGE 已經結束一陣子了，原本 TGE 的文件跟其他資訊應該要找個地方歸檔。目標是：
1. 使用者進來可以了解專案的目的
2. 知道要怎麼開始貢獻如協助組織社群、撰寫文章以及提案
3. 代幣分配、TGE 等等歸檔放到其他頁面去

**Comment by quesalltime** [comment]
這部分我可以來處理，
想要討論一下各種資訊的`歸檔原則`是什麼，包含：
- 不同種類的README.md，是否需要置放到不同的資料夾(哪個路徑)？或是統一單個資料夾？
- 將目前需要歸檔的資訊條列，已知的有(若有缺漏請補充)
  - [ ] TGE說明
  - [ ] 代幣分配

**Comment by yurenju** [comment]
我覺得可以把它放到 [src/pages][1] 裡面，我們那邊現在有 [publish-guideline.md][2]，並且可以在 https://lundao.tech/publish-guideline 存取，感覺 TGE 應該也是一個頁面並且標示為已結束，代幣分配也是可以自己一頁，但是 Pull Request #62 已經有一頁新的 LUN 代幣 (src/pages/lun-token-usage.md)，也可以考慮合併到此。

[1]: https://github.com/lun-dao/LunDAO/tree/main/src/pages
[2]: https://github.com/lun-dao/LunDAO/blob/main/src/pages/publish-guideline.md

**Comment by yurenju** [comment]
fixed on #65
