### ISSUE TITLE
Hardhat Forking 使用

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#71]
Hardhat 是 Ethereum 的開發工具組，提供了一個框架讓開發者可以在上面撰寫智能合約、測試與部署。其中 Forking 工具可以讓開發者以 Production 環境的資料直接執行各種交易來達成更完善的測試環境。

**目標讀者**：這篇文章讀者的背景
- 正在開發智能合約，想更深入的了解上線前需要的測試步驟
- 大略知道 Forking 是什麼，但不清楚實際上要怎麼使用

**讀者應具備知識**：讀者在閱讀這篇文章前所需要具備的知識
- 開發過智能合約
- 部署過智能合約在測試網路

**閱讀完畢後讀者會知道**：閱讀完之後讀者所會獲得的新知識
- Forking 是什麼
- Forking 怎麼在 Production 環境下使用
- 怎麼模擬一個使用者，模擬他的身份發出交易

**你所提供的 LUN 代幣獎勵**：
- 150 LUN - tx on [arbiscan][1]

[1]: https://arbiscan.io/tx/0x084348b835bf68539bd64ebb000fcbe2fc1d0f2e33b9800889a05c886f64de93

**Comment by a2468834** [comment]
Hi~ 剛剛才發現這個酷炫 repo
因為不太了解這邊的生態，所以來提問一下：

請問這則 issue 是公開徵求文章的意思嗎？
（最近剛好有要來研究 mainnet fork 怎麼用）

還是說是個 PR request 呢？
（如果是的話希望能提供文章連結，滿想熟悉 mainnet fork 的功能）

**Comment by a2468834** [comment]
自我回答一下自己的提問：

這是一則公開徵文的 issue，詳情請見[這邊的文字](https://github.com/lun-dao/LunDAO/blob/e52e9e894ed85486137cc7004cd104531699b5ee/docs/publish-guideline.md?plain=1#L20)

**Comment by yurenju** [comment]
沒錯這是公開徵文的連結，有興趣的話也可以研究研究來投稿喔！

**Comment by yurenju** [comment]
close via commit 7252c7502269369349e87d1294e9cd07fa9ab857
