### ISSUE TITLE
新增其他 issue template

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#73]
現在只有 RFA template，雖然可以按左下角有一個很小的 create blank issue 不過太不明顯了，所以還會需要加幾個 template 讓開 issue 的體驗好一點

**Comment by hydai** [comment]
目前我們還需要哪些 issue template?
1. RFA
2. ?

**Comment by gasolin** [comment]
1. RFA
2. Web Site Issue
3. Article feedback (在發布後可能有些情況反饋)

**Comment by yurenju** [comment]
3 好像比較適合寫在 Github Discussion 裡面，比如說發表一篇文章後，就直接開一個 Github Discussion 來讓大家有更多討論，可以先手動，之後再串 API
