### ISSUE TITLE
六月份獎勵發送

### ISSUE THREAD

**Issue by yurenju** [lun-dao/LunDAO#96]
以下有兩個要簽名的工作：
- [x] 社群獎勵，請參考 [試算表](https://docs.google.com/spreadsheets/d/1f7KCZ0Ki1wnXFDwmdUbJIvZAZbVYvR2VrYILKmgtdGs/edit#gid=646687921)
- [x] 寫作獎勵，請參考 [文章列表](https://lundao.tech/blog/) 與 [contributors.csv](https://github.com/lun-dao/LunDAO/blob/main/contributors.csv)本次是 @yurenju @wiasliaw @a2468834 
- [x] 編輯文件加入這次獎勵資訊

@hydai 再麻煩你幫忙檢查跟簽名一下，感謝

**Comment by hydai** [comment]
我想確認一下寫作獎勵的數字？都是 `500000000000000000000` 嗎？

**Comment by hydai** [comment]
社群獎勵的部分我已經確認，等待寫作獎勵的細節確認

**Comment by yurenju** [comment]
@hydai 對，可以參考這個頁面 https://lundao.tech/docs/publish-reward
固定 500 LUN = 500 * 10^18 = 500_000_000_000_000_000_000 總共是 5 後面再加上 20 個零

**Comment by hydai** [comment]
都確認了，請執行

**Comment by yurenju** [comment]
執行了，晚點把文件更新上去
https://arbiscan.io/tx/0x5a5413f95941bcd03776521e74cb6a5e091b7d1a4abcf3902bd5c74f73ea9d60

**Comment by yurenju** [comment]
完成囉！ commit 9949f1cf4358c944032fd12a4086336ea89253e3
